### ISSUE TITLE
Small nits about how to get started (tracking issue)

### ISSUE THREAD

**Issue by cecton** [yewprint/yewprint#73]
I'm creating this PR to make a list and keep track of all the small nits that makes it harder to use or get started with yewprint (and yew in general). Please comment on this PR your ideas and your proposals to mitigate or solve the issues.

- [ ] Getting started tutorial: there are instructions for yew but it is not their strong point either.
    - [ ] We should probably make a template
    - [x] @Yozhgoor is working on a real life example 
    - [ ] with lot of simple examples and comments
    - [x] I'm adding rustup to the netlify image so our template repository will also be able to provide a default configuration https://github.com/netlify/build-image/pull/477
    - [ ] wasm-run doesn't work on netlify anymore (can't build binaryen)
- [ ] Build tools: there is quite some setup to do before being able to even start: wasm-pack, cargo-watch (I think that one is optional as you can do the same with wasm-pack)
    - [x] @cecton is currently working on a new tooling library that should make it a lot easier
- [ ] Classes: yewprint component's "class" props are `String` and harder to use than base components (div, span, ...)
    - [ ] Solved in https://github.com/yewstack/yew/pull/1601(waiting for a release)
- [ ] Lack of API ref documentation
    - [x] Temporarily hosted on https://yewprint.rm.rs/api/yewprint/
    - [ ] Will be hosted on docs.rs when we fix the version of yew
- [ ] Icon generation sometimes fail silenty. I saw that with @Yozhgoor that if the build script fails you can end up with errors saying that there are missing `IconName`s.
    - [ ] We can try to make the script more resilient I guess (make it fail more so errors are not silent)
    - [ ] I don't know how to reproduce so we need to keep track on that to see if the issue disappears at some point
- [ ] OS compatibility
    - [ ] None of the scripts are made for Windows so it won't work on it
    - [ ] We could add builds for Windows and OSX

@Yozhgoor @rbeard0330 @oScape @EstebanBorai @nbrr did you have other issues? Don't hesitate to report them here

**Comment by EstebanBorai** [comment]
Hey @cecton! I think this is stale, should we close this?

**Comment by cecton** [comment]
Yes I guess
